CREATE DATABASE IF NOT EXISTS usuarios_service;
CREATE DATABASE IF NOT EXISTS vehiculos_service;
CREATE DATABASE IF NOT EXISTS service_requests_db;
CREATE DATABASE IF NOT EXISTS services_db;
CREATE DATABASE IF NOT EXISTS reviews_db;
